# Public API
#
# Keep exports separate from module assembly so `LifeAI.jl` describes the
# dependency order of the implementation. Grouping by responsibility also
# makes additions to the public surface deliberate and reviewable.

# Core model components
export MultiHeadAttention
export manual_scaled_dot_product_attention
export batched_scaled_dot_product_attention
export repeat_kv
export RMSNormLayer, SwiGLU, Qwen3SparseMoE, qwen3_topk_routing
export qwen3_device_topk_routing, qwen3_device_sparse_expert_dispatch
export qwen3_cuda_indexed_workspace_bytes
export Qwen3MoEDispatchStats, qwen3_dense_expert_reference
export qwen3_sparse_expert_dispatch, qwen3_moe_forward_with_stats
export qwen3_moe_device_forward
export TransformerBlock, gelu_new
export RoPE, apply_rope
export SamplingSchedule

# Tokenization and datasets
export AbstractTokenizer, Tokenizer, ByteTokenizer, ByteBPETokenizer
export HFQwen3Tokenizer, HFQwen3GenerationConfig
export HFGPT2Tokenizer, HFGPT2GenerationConfig
export hf_byte_unicode_alphabet, load_hf_qwen3_tokenizer, hf_generation_config
export load_hf_qwen3_vl_tokenizer, apply_qwen3_vl_chat_template
export load_hf_qwen3_embedding_tokenizer
export hf_qwen3_pretokenize, apply_qwen3_chat_template
export OrderedJSONObject, parse_qwen3_json
export load_hf_gpt2_tokenizer, hf_gpt2_pretokenize
export fit_tokenizer, fit_byte_bpe, encode, decode, decode_bytes, vocab_size
export normalize_text, special_token_id, token_byte_length, encoded_byte_length
export tokenizer_config, tokenizer_fingerprint, tokenizer_statistics
export MAX_DIFFUSION_STEPS, DiffusionSchedule, linear_diffusion_schedule, scaled_linear_diffusion_schedule
export cosine_diffusion_schedule, diffusion_coefficients, diffusion_snr, diffusion_logsnr
export validate_diffusion_schedule, diffusion_beta, diffusion_alpha, diffusion_alpha_cumprod
export diffusion_previous_alpha_cumprod, diffusion_posterior_variance
export diffusion_posterior_mean_coefficients, diffusion_posterior_mean
export diffusion_ddim_step, diffusion_min_snr_weight, diffusion_p2_weight
export diffuse_sample, diffusion_sample_from_epsilon, diffusion_epsilon_from_sample
export diffusion_velocity, diffusion_sample_from_velocity, diffusion_epsilon_from_velocity
export TOKENIZER_ARTIFACT_VERSION, save_tokenizer, load_tokenizer
export DatasetLoader, DocumentDatasetLoader, num_samples, num_batches, target_byte_count
export split_token_stream, split_text_stream, train_validation_loaders
export TextDocument, load_text_documents, split_documents, build_document_dataset
export DATASET_ARTIFACT_VERSION, save_dataset_artifact, load_dataset_artifact

# Models and HuggingFace interoperability
export GPTModel, TiedOutputProjection, gpt_config
export Qwen3DenseSpec, qwen3_dense_specs, qwen3_dense_spec
export qwen3_dense_parameter_count
export load_hf_qwen3_config, load_safetensors, load_hf_qwen3_parameters
export load_hf_qwen3_model, hf_token_ids, hf_qwen3_forward_trace
export load_hf_qwen3_moe_config, load_hf_qwen3_moe_parameters
export load_hf_qwen3_moe_model, hf_qwen3_moe_forward_trace
export Qwen3MoECheckpointSpec, Qwen3MoEShardSpec
export qwen3_moe_checkpoint_spec, qwen3_moe_parameter_count
export verify_qwen3_moe_checkpoint
export Qwen3EmbeddingSpec, qwen3_embedding_spec
export qwen3_embedding_parameter_count
export load_hf_qwen3_embedding_config, verify_qwen3_embedding_assets
export load_hf_qwen3_embedding_model, load_hf_qwen3_embedding_bundle
export HFSafetensorsReader, open_safetensors_reader, read_safetensors_tensor,
    read_safetensors_tensors
export Qwen3VLAssetSpec, Qwen3VLTextSpec, Qwen3VLVisionSpec
export Qwen3VLCheckpointSpec, qwen3_vl_checkpoint_spec
export qwen3_vl_parameter_count, qwen3_vl_expected_tensor_shapes
export load_hf_qwen3_vl_config, verify_qwen3_vl_checkpoint
export Qwen3VLProcessorSpec, qwen3_vl_processor_spec
export load_hf_qwen3_vl_processor_config, qwen3_vl_smart_resize
export qwen3_vl_image_grid, qwen3_vl_image_token_count, qwen3_vl_patchify
export Qwen3VLProcessedImage, qwen3_vl_process_image
export qwen3_vl_expand_image_placeholders, Qwen3VLRopeLayout
export qwen3_vl_rope_layout
export Qwen3VLVisionInput, Qwen3VLVisionFeatures
export load_hf_qwen3_vl_vision_parameters, hf_qwen3_vl_vision_forward
export Qwen3VLTextPrefill, load_hf_qwen3_vl_text_parameters
export hf_qwen3_vl_text_prefill, hf_qwen3_vl_prefill
export Qwen3VLKVCache, init_qwen3_vl_kv_cache
export hf_qwen3_vl_text_prefill_cached, hf_qwen3_vl_text_decode_step
export Qwen3VLStaticLayerKVCache, Qwen3VLStaticKVCache
export init_qwen3_vl_static_kv_cache, reset_qwen3_vl_static_kv_cache!
export hf_qwen3_vl_text_prefill_static, hf_qwen3_vl_text_decode_step_static
export generate_hf_qwen3_vl_tokens, generate_hf_qwen3_vl
export stream_hf_qwen3_forward, stream_hf_qwen3_moe_forward
export load_hf_qwen3_compact_model, load_hf_qwen3_compact_bundle
export hf_qwen3_bf16_forward
export hf_qwen3_bf16_accel_forward
export QWEN3_EMBEDDING_RETRIEVAL_INSTRUCTION
export qwen3_embedding_query, prepare_qwen3_embedding_inputs
export qwen3_last_token_pool, hf_qwen3_embedding_forward, embed_texts
export qwen3_embedding_similarity
export Qwen3SemanticMemory, build_qwen3_semantic_memory
export retrieve_qwen3_semantic_memory, search_qwen3_semantic_memory
export Int8ChannelWeight, Int4GroupWeight, quantize_bf16_parameters
export LinearQuantizationSpec, QuantizationPlan, quantization_spec
export ActivationCalibration, activation_second_moment
export calibrate_hf_qwen3_activations
export quantized_parameter_bytes, estimate_qwen3_quantized_bytes
export load_hf_qwen3_quantized
export load_hf_qwen3_bundle, generate_hf_text
export Qwen3DeploymentProfile, load_qwen3_deployment_profile
export verify_qwen3_deployment_assets
export qwen3_kv_cache_bytes
export HFQwen3BF16Session, init_hf_qwen3_bf16_session
export load_hf_qwen3_bf16_session, reset_hf_qwen3_bf16_session!
export prefill_hf_qwen3_bf16!, decode_hf_qwen3_bf16!
export generate_hf_qwen3_bf16!, generate_hf_text!, fit_qwen3_chat_context
export HFQwen3MoEOffloadSession, qwen3_moe_offload_plan
export load_hf_qwen3_moe_offload_session
export reset_hf_qwen3_moe_offload_session!
export clear_hf_qwen3_moe_expert_cache!, qwen3_moe_expert_cache_stats
export configure_hf_qwen3_moe_expert_cache!
export prefill_hf_qwen3_moe_offload!, decode_hf_qwen3_moe_offload!
export Qwen3XLAWindowPlan, plan_qwen3_xla_window
export qwen3_xla_pad_prompt, qwen3_xla_key_positions
export HFQwen3BF16XLASession, load_hf_qwen3_bf16_xla_session
export reset_hf_qwen3_bf16_xla_session!, generate_hf_qwen3_bf16_xla!
export device_sample_token
export Qwen3XLAHTTPService, load_qwen3_xla_http_service
export qwen3_xla_service_status, qwen3_xla_http_handler
export qwen3_xla_http_stream_handler, serve_qwen3_xla_http!
export load_hf_gpt2_config, load_hf_gpt2_parameters, load_hf_gpt2_model
export load_hf_gpt2_bundle, hf_gpt2_forward_trace

# Tool declarations and the minimal agent loop
export AgentTool, ToolRegistry, qwen3_tool_specs, default_agent_tools
export calculator_tool, evaluate_arithmetic
export Qwen3ToolCall, Qwen3ToolCallParse, parse_qwen3_tool_calls
export AgentToolResult, invoke_agent_tool, agent_tool_call_validity
export AgentLoopStep, AgentLoopTrace, run_qwen3_tool_loop, run_qwen3_memory_loop
export agent_loop_summary, wilson_interval

# Persistent exact semantic memory and retrieval context
export AGENT_MEMORY_FORMAT_VERSION
export MAX_AGENT_MEMORY_JOURNAL_BYTES, MAX_AGENT_MEMORY_RECORD_BYTES
export MAX_AGENT_MEMORY_RECORDS, MAX_AGENT_MEMORY_TEXT_BYTES
export MAX_AGENT_MEMORY_METADATA_ENTRIES, MAX_AGENT_MEMORY_METADATA_KEY_BYTES
export MAX_AGENT_MEMORY_METADATA_VALUE_BYTES, MAX_AGENT_MEMORY_METADATA_BYTES
export AgentMemoryRecord, AgentMemoryStore
export load_agent_memory_store, append_agent_memory!, agent_memory_fingerprint
export AgentMemoryIndex, AgentMemoryHit, AgentMemoryContext
export build_agent_memory_index, retrieve_agent_memory, search_agent_memory
export render_agent_memory_context, agent_memory_context
export validate_agent_memory_context
export retrieve_agent_memory_context, select_agent_memory_context
export search_agent_memory_context

# Deterministic environment/action loop
export AGENT_ENVIRONMENT_FORMAT_VERSION, AGENT_ENVIRONMENT_TRACE_FORMAT_VERSION
export AbstractAgentEnvironment
export GridWorldSpec, GridWorldEnvironment, gridworld_spec_fingerprint
export AgentEnvironmentObservation, AgentEnvironmentAction
export AgentEnvironmentTransition, AgentEnvironmentTrace
export reset_agent_environment!, observe_agent_environment
export step_agent_environment!, gridworld_legal_actions
export render_agent_environment_feedback, gridworld_move_tool
export gridworld_tool_registry, gridworld_system_prompt, gridworld_user_prompt
export run_qwen3_environment_loop, agent_environment_summary
export agent_environment_trace_payload, replay_qwen3_environment_trace
export gridworld_shortest_actions, replay_gridworld_actions

# Explicit environment-event memory writeback
export AGENT_ENVIRONMENT_MEMORY_EVENT_VERSION
export AgentEnvironmentMemoryPolicy, AgentEnvironmentMemoryEvent
export AgentEnvironmentMemoryWriteback
export gridworld_successful_episode_memory_policy
export gridworld_memory_query, gridworld_memory_system_prompt
export gridworld_memory_writer_system_prompt
export agent_environment_memory_events, append_agent_environment_events!
export validate_agent_environment_memory_record
export agent_environment_memory_records
export retrieve_gridworld_memory_context, select_gridworld_memory_context

# Task-level quality evaluation
export MMLUItem, GSM8KItem, EvalTaskSet, EvalItemResult, load_eval_tasks
export mmlu_loglikelihood_prompt, mmlu_chat_messages, gsm8k_chat_messages
export mmlu_loglikelihood_scores, extract_mmlu_letter, extract_gsm8k_answer
export gsm8k_answer_matches, accuracy_report, subject_report
export paired_comparison, mcnemar_exact
export AgentMemoryTask, AgentMemoryTaskSet, load_agent_memory_tasks
export seed_agent_memory_tasks!, extract_agent_memory_answer
export agent_memory_answer_matches, agent_memory_retrieval_report
export GridWorldTask, GridWorldTaskSet, load_gridworld_tasks
export gridworld_task_result, gridworld_task_report

# Training and persistence
export TrainerGPT, init_train_state, next_token_loss, next_token_nll_sum
export global_gradient_norm, clip_global_gradient_norm
export train_step!, train_gpt!
export evaluate_gpt, bits_per_byte
export CHECKPOINT_FORMAT_VERSION, save_checkpoint, load_checkpoint, resume_gpt!

# Generation and KV caches
export generate
export LayerKVCache, GPTKVCache, init_kv_cache, prefill, decode_step, generate_cached
export StaticLayerKVCache, StaticGPTKVCache, init_static_kv_cache
export XLAKVDecoder, xla_prefill!, xla_decode_step!, generate_xla_cached!
export kv_cache_correctness, benchmark_kv_cache, benchmark_xla_kv_cache
export benchmark_xla_cache_modes
