# Public API
#
# Keep exports separate from module assembly so `LifeAI.jl` describes the
# dependency order of the implementation. Grouping by responsibility also
# makes additions to the public surface deliberate and reviewable.

# Core model components
export MultiHeadAttention
export manual_scaled_dot_product_attention
export batched_scaled_dot_product_attention
export repeat_kv
export RMSNormLayer, SwiGLU, Qwen3SparseMoE, qwen3_topk_routing
export qwen3_device_topk_routing, qwen3_device_sparse_expert_dispatch
export qwen3_cuda_indexed_workspace_bytes
export Qwen3MoEDispatchStats, qwen3_dense_expert_reference
export qwen3_sparse_expert_dispatch, qwen3_moe_forward_with_stats
export qwen3_moe_device_forward
export TransformerBlock, gelu_new
export RoPE, apply_rope
export SamplingSchedule

# Tokenization and datasets
export AbstractTokenizer, Tokenizer, ByteTokenizer, ByteBPETokenizer
export HFQwen3Tokenizer, HFQwen3GenerationConfig
export HFGPT2Tokenizer, HFGPT2GenerationConfig
export hf_byte_unicode_alphabet, load_hf_qwen3_tokenizer, hf_generation_config
export load_hf_qwen3_embedding_tokenizer
export hf_qwen3_pretokenize, apply_qwen3_chat_template
export OrderedJSONObject, parse_qwen3_json
export load_hf_gpt2_tokenizer, hf_gpt2_pretokenize
export fit_tokenizer, fit_byte_bpe, encode, decode, decode_bytes, vocab_size
export normalize_text, special_token_id, token_byte_length, encoded_byte_length
export tokenizer_config, tokenizer_fingerprint, tokenizer_statistics
export TOKENIZER_ARTIFACT_VERSION, save_tokenizer, load_tokenizer
export DatasetLoader, DocumentDatasetLoader, num_samples, num_batches, target_byte_count
export split_token_stream, split_text_stream, train_validation_loaders
export TextDocument, load_text_documents, split_documents, build_document_dataset
export DATASET_ARTIFACT_VERSION, save_dataset_artifact, load_dataset_artifact

# Models and HuggingFace interoperability
export GPTModel, TiedOutputProjection, gpt_config
export Qwen3DenseSpec, qwen3_dense_specs, qwen3_dense_spec
export qwen3_dense_parameter_count
export load_hf_qwen3_config, load_safetensors, load_hf_qwen3_parameters
export load_hf_qwen3_model, hf_token_ids, hf_qwen3_forward_trace
export load_hf_qwen3_moe_config, load_hf_qwen3_moe_parameters
export load_hf_qwen3_moe_model, hf_qwen3_moe_forward_trace
export Qwen3MoECheckpointSpec, Qwen3MoEShardSpec
export qwen3_moe_checkpoint_spec, qwen3_moe_parameter_count
export verify_qwen3_moe_checkpoint
export Qwen3EmbeddingSpec, qwen3_embedding_spec
export qwen3_embedding_parameter_count
export load_hf_qwen3_embedding_config, verify_qwen3_embedding_assets
export load_hf_qwen3_embedding_model, load_hf_qwen3_embedding_bundle
export HFSafetensorsReader, open_safetensors_reader, read_safetensors_tensor,
    read_safetensors_tensors
export stream_hf_qwen3_forward, stream_hf_qwen3_moe_forward
export load_hf_qwen3_compact_model, load_hf_qwen3_compact_bundle
export hf_qwen3_bf16_forward
export hf_qwen3_bf16_accel_forward
export QWEN3_EMBEDDING_RETRIEVAL_INSTRUCTION
export qwen3_embedding_query, prepare_qwen3_embedding_inputs
export qwen3_last_token_pool, hf_qwen3_embedding_forward, embed_texts
export qwen3_embedding_similarity
export Qwen3SemanticMemory, build_qwen3_semantic_memory
export retrieve_qwen3_semantic_memory, search_qwen3_semantic_memory
export Int8ChannelWeight, Int4GroupWeight, quantize_bf16_parameters
export LinearQuantizationSpec, QuantizationPlan, quantization_spec
export ActivationCalibration, activation_second_moment
export calibrate_hf_qwen3_activations
export quantized_parameter_bytes, estimate_qwen3_quantized_bytes
export load_hf_qwen3_quantized
export load_hf_qwen3_bundle, generate_hf_text
export Qwen3DeploymentProfile, load_qwen3_deployment_profile
export verify_qwen3_deployment_assets
export qwen3_kv_cache_bytes
export HFQwen3BF16Session, init_hf_qwen3_bf16_session
export load_hf_qwen3_bf16_session, reset_hf_qwen3_bf16_session!
export prefill_hf_qwen3_bf16!, decode_hf_qwen3_bf16!
export generate_hf_qwen3_bf16!, generate_hf_text!, fit_qwen3_chat_context
export HFQwen3MoEOffloadSession, qwen3_moe_offload_plan
export load_hf_qwen3_moe_offload_session
export reset_hf_qwen3_moe_offload_session!
export clear_hf_qwen3_moe_expert_cache!, qwen3_moe_expert_cache_stats
export configure_hf_qwen3_moe_expert_cache!
export prefill_hf_qwen3_moe_offload!, decode_hf_qwen3_moe_offload!
export Qwen3XLAWindowPlan, plan_qwen3_xla_window
export qwen3_xla_pad_prompt, qwen3_xla_key_positions
export HFQwen3BF16XLASession, load_hf_qwen3_bf16_xla_session
export reset_hf_qwen3_bf16_xla_session!, generate_hf_qwen3_bf16_xla!
export device_sample_token
export Qwen3XLAHTTPService, load_qwen3_xla_http_service
export qwen3_xla_service_status, qwen3_xla_http_handler
export qwen3_xla_http_stream_handler, serve_qwen3_xla_http!
export load_hf_gpt2_config, load_hf_gpt2_parameters, load_hf_gpt2_model
export load_hf_gpt2_bundle, hf_gpt2_forward_trace

# Tool declarations and the minimal agent loop
export AgentTool, ToolRegistry, qwen3_tool_specs, default_agent_tools
export Qwen3ToolCall, Qwen3ToolCallParse, parse_qwen3_tool_calls
export AgentToolResult, invoke_agent_tool, agent_tool_call_validity
export AgentLoopStep, AgentLoopTrace, run_qwen3_tool_loop
export agent_loop_summary, wilson_interval

# Training and persistence
export TrainerGPT, init_train_state, next_token_loss, next_token_nll_sum
export global_gradient_norm, clip_global_gradient_norm
export train_step!, train_gpt!
export evaluate_gpt, bits_per_byte
export CHECKPOINT_FORMAT_VERSION, save_checkpoint, load_checkpoint, resume_gpt!

# Generation and KV caches
export generate
export LayerKVCache, GPTKVCache, init_kv_cache, prefill, decode_step, generate_cached
export StaticLayerKVCache, StaticGPTKVCache, init_static_kv_cache
export XLAKVDecoder, xla_prefill!, xla_decode_step!, generate_xla_cached!
export kv_cache_correctness, benchmark_kv_cache, benchmark_xla_kv_cache
export benchmark_xla_cache_modes
